name: Run Unit Test
on: [push, pull_request]
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Download spacy data
        run: python -m spacy download en_core_web_sm
      - name: Run tests
        working-directory: ./tests
        run: python -m unittest test_extract_dataframe.py
      - run: echo "Status is ${{ job.status }}."
