name: Run Unit Test
on: [push, pull_request]
jobs:
  run-test-on-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download spacy data
        run: python -m spacy download en_core_web_sm
      - name: Test with unittest
        run: |
          python -m unittest
